# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello( to ):
    "my doc string: say_hello returns the string 'Bonsoir cher _to_'"
    return f"Bonsoir cher {to}"
